config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
    patch :apply_role, on: :member
  end
  
  resources :roles do
    collection do
      get 'list'
    end
    patch :apply_permission, on: :member
  end

  resources :plans, module: :client, as: :client_plans do
    collection do
      get 'list'
    end
  end

  resources :charts

  resources :clients do
    collection do
      get 'list'
    end
    resources :invoices, module: :client, only: [:index, :show] do
      patch :retry, on: :member
      resources :error_logs, module: :invoice, only: [:index, :show]
    end
  end

  namespace :reports do
    get :new_clients
    get :clients_invoiced_yesterday
    get :clients_invoiced_today
    get :clients_with_error_today
    get :clients
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!
  # has_secure_password :password, validations: true

  has_and_belongs_to_many :roles
  has_many :permissions, through: :roles

  has_many :created_clients, class_name: 'Client',
                             inverse_of: :created_by,
                             dependent: :destroy,
                             foreign_key: :created_by_id

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  # To be reimplemented
  # before_update :at_least_one_admin
  # before_destroy :at_least_one_admin

  # def at_least_one_admin
  #  User.where(admin: true).where.not(id:)
  # end

  def admin?
    roles.where(code: 'admin').present?
  end

  def name
    "#{first_name} #{last_name}"
  end
end

# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  first_name       :string
#  last_name        :string
#  email            :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  crypted_password :string
#  salt             :string
#

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_users, only: %i[index list]
  before_action :set_user, only: %i[show edit update destroy apply_role]
  before_action :set_roles, only: %i[show apply_role]

  # GET /users or /users.json
  def index; end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    authorize User
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params.merge(password_params))
    authorize @user

    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created.'
        format.html { redirect_to user_url(@user) }
      else
        flash[:error] = 'User not created'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    all_params = user_params
    all_params.merge!(password_params) if password_params[:password].present? && password_params[:password_confirmation].present?
    respond_to do |format|
      if @user.update(all_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to user_url(@user) }
      else
        flash[:error] = 'User not updated'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    respond_to do |format|
      if @user.destroy
        flash[:success] = 'User was successfully destroyed.'
      else
        flash[:error] = 'User not deleted'
      end
      format.html { redirect_to users_url }
    end
  end

  def list
    render(partial: 'users/table', locals: { users: @users })
  end

  def apply_role
    role = @user.roles.find_by(id: params[:role_id])
    if role.present?
      @user.roles.delete(role)
    else
      @user.roles << Role.find_by(id: params[:role_id])
    end
    render(partial: 'users/roles', locals: { roles: @roles })
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def set_users
    authorize User

    @users = User.all
    sort_users
    @pagy, @users = pagy(@users)
  end

  def allow_sort
    %w[id name email admin].include?(params[:sort_by].to_s)
  end

  def sort_users
    return unless allow_sort

    sort_order = params[:sort_order] == 'DESC' ? 'DESC' : 'ASC'
    sort = if params[:sort_by] == 'name'
             { first_name: sort_order, last_name: sort_order }
           else
             { params[:sort_by].to_sym => sort_order }
           end

    @users = @users.order(sort)
  end

  def set_roles
    @roles = Role.all
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if user.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.text_field :first_name, class: "form-control", readonly: readonly %>
        <%= form.label :first_name %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.text_field :last_name, class: "form-control", readonly: readonly %>
        <%= form.label :last_name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-10 mb-1">
      <div class="form-floating">
        <%= form.email_field :email, class: "form-control", readonly: readonly %>
        <%= form.label :email %>
      </div>
    </div>
    <div class="col-sm-12 col-md-2 mb-1">
      <div class="form-floating">
        <%= form.select :admin, [['No', false], ['Yes', true]], {}, class: "form-select", disabled: readonly || !current_user.admin? %>
        <%= form.label :admin %>
      </div>
    </div>
  </div>
  <% unless readonly %>
    <div class="row">
      <div class="col-sm-12 col-md-6 mb-1">
        <div class="form-floating">
          <%= form.password_field :password, class: "form-control" %>
          <%= form.label :password %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6 mb-1">
        <div class="form-floating">
          <%= form.password_field :password_confirmation, class: "form-control" %>
          <%= form.label :password_confirmation %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= form.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_roles.html.erb
<%= turbo_frame_tag "users_roles" do %>
  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped table-sm">
        <tbody>
          <% roles.each do |role| %>
            <tr>
              <td>
                <%= link_to role.name, role_path(role), data: { turbo: false } %>
              </td>
              <td>
                <%= link_to apply_role_user_path(@user.id, role_id: role.id), data: {turbo_method: :patch} do %>
                  <div class="form-check form-switch">
                    <%= check_box_tag :allowed, :allowed, false, class: 'form-check-input', checked: @user.roles.where(id: role.id).present? %>
                  </div>
                <% end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/users/_table.html.erb
<%= turbo_frame_tag "users_table" do %>
  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">
              <%= sort_link(column: :id, label: '#', controller: :users, action: 'list') %>
            </th>
            <th scope="col">
              <%= sort_link(column: :name, label: 'Name', controller: :users, action: 'list') %>
            </th>
            <th scope="col">
              <%= sort_link(column: :email, label: 'Email', controller: :users, action: 'list') %>
            </th>
            <th scope="col">
              Roles
            </th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.name, user_path(user), data: { turbo: false } %></td>
              <td><%= user.email %></td>
              <td><%= user.roles.pluck(:name).join(', ') %></td>
              <td>
                <div class="btn-group me-2">
                  <%= link_to user_path(user), class: "btn btn-sm btn-outline-secondary", data: { turbo: false } do %>
                    <i class="bi bi-eye"></i>
                  <% end %>
                  <% if current_user.admin? || current_user.id == user.id %>
                    <% if current_user.id != user.id %>
                      <%= link_to user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                        <i class="bi bi-trash"></i>
                      <% end %>
                    <% end %>
                    <%= link_to edit_user_path(user), class: "btn btn-sm btn-outline-primary", data: { turbo: false } do %>
                      <i class="bi bi-pencil-square"></i>
                    <% end %>
                  <% end%>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render "shared/pagination" %>
<% end %>

app/views/users/edit.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">Editing <%= @user.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <%= link_to @user, class: "btn btn-sm btn-outline-primary" do %>
              <i class="bi bi-eye"></i> Show
            <% end %>
            <%= link_to users_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Users
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "form", user: @user, readonly: false %>
</div>

app/views/users/index.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
        <% if current_user.admin? %>
          <div class="btn-toolbar mb-2 mb-md-0 mx-2">
            <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-person-plus"></i> New User
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "table", users: @users%>
</div>

app/views/users/new.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">New user</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <%= link_to users_path, class: "btn btn-sm btn-outline-secondary" do %>
            <i class="bi bi-arrow-return-left"></i> Back to Users
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", user: @user, readonly: false %>
</div>

app/views/users/show.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2"><%= @user.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <% if current_user.admin? || current_user.id == @user.id %>
              <% if current_user.id != @user.id %>
                <%= link_to user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                  <i class="bi bi-trash"></i> Delete
                <% end %>
              <% end %>
              <%= link_to edit_user_path(@user), class: "btn btn-sm btn-outline-primary" do %>
                <i class="bi bi-pencil-square"></i> Edit
              <% end %>
            <% end%>
            <%= link_to users_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Users
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", user: @user, readonly: true %>

  <div class="row">
    <div class="col-12">
    <div class="card">
      <div class="card-body">
          <h5>Roles</h5>
          <%= render "users/roles", roles: @roles %>
        </div>
      </div>
    </div>
  </div>

</div>