config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
    patch :apply_role, on: :member
  end
  
  resources :roles do
    collection do
      get 'list'
    end
    patch :apply_permission, on: :member
  end

  resources :plans, module: :client, as: :client_plans do
    collection do
      get 'list'
    end
  end

  resources :charts

  resources :clients do
    collection do
      get 'list'
    end
    resources :invoices, module: :client, only: [:index, :show] do
      patch :retry, on: :member
      resources :error_logs, module: :invoice, only: [:index, :show]
    end
  end

  namespace :reports do
    get :new_clients
    get :clients_invoiced_yesterday
    get :clients_invoiced_today
    get :clients_with_error_today
    get :clients
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/views/shared/_flash.html.erb
<div class="alert <%= flash_class_for(msg_type) %>">
  <div class="container">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= message %>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="col-sm-auto bg-light sticky-top">
  <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top">
      <a href="/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right">
          <h2>FJ</h2>
      </a>
      <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
        <div class="dropdown">
          <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi-briefcase fs-1"></i>
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
            <li><a href=<%= charts_path %> class="dropdown-item">Charts</a></li>
            <li><a href=<%= clients_path %> class="dropdown-item">Clients</a></li>
            <li><a href=<%= client_plans_path %> class="dropdown-item">Plans</a></li>
          </ul>
        </div>
        <div class="dropdown">
          <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi-people fs-1"></i>
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
            <li><a href=<%= users_path %> class="dropdown-item">Users</a></li>
            <li><a href=<%= roles_path %> class="dropdown-item">Roles</a></li>
          </ul>
        </div>
          <div class="dropdown">
            <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi-table fs-1"></i>
            </a>
            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
                <li><a class="dropdown-item" href=<%= reports_new_clients_path %>>New Clients</a></li>
                <li><a class="dropdown-item" href=<%= reports_clients_with_error_today_path %>>Clients With Error Today</a></li>
                <li><a class="dropdown-item" href=<%= reports_clients_invoiced_today_path %>>Clients Invoiced Today</a></li>
                <li><a class="dropdown-item" href=<%= reports_clients_invoiced_yesterday_path %>>Clients Invoiced Yesterday</a></li>
                <li><a class="dropdown-item" href=<%= reports_clients_path %>>Clients</a></li>
            </ul>
          </div>
      </ul>
      <div class="dropdown">
          <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi-person-circle h2"></i>
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
              <li><a class="dropdown-item" href=<%= user_path(@current_user) %>>My Profile</a></li>
              <li><a class="dropdown-item" href=<%= logout_path %>>Logout</a></li>
          </ul>
      </div>
  </div>
</div>

app/views/shared/_notices.html.erb
<div id="flash">
  <% flash.each do |msg_type, message| %>
    <%= render partial: "shared/flash", locals: { msg_type: msg_type, message: message } %>
  <% end %>
</div>

app/views/shared/_pagination.html.erb
<div class="row">
  <div class="col-12">
    <div class="d-flex justify-content-center">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>