config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
    patch :apply_role, on: :member
  end
  
  resources :roles do
    collection do
      get 'list'
    end
    patch :apply_permission, on: :member
  end

  resources :plans, module: :client, as: :client_plans do
    collection do
      get 'list'
    end
  end

  resources :charts

  resources :clients do
    collection do
      get 'list'
    end
    resources :invoices, module: :client, only: [:index, :show] do
      patch :retry, on: :member
      resources :error_logs, module: :invoice, only: [:index, :show]
    end
  end

  namespace :reports do
    get :new_clients
    get :clients_invoiced_yesterday
    get :clients_invoiced_today
    get :clients_with_error_today
    get :clients
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions

  validates :name, :code, presence: true
end

# == Schema Information
#
# Table name: roles
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  code        :string
#  active      :boolean          default(TRUE)
#  deletable   :boolean          default(TRUE)
#  editable    :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/roles_controller.rb
# frozen_string_literal: true

class RolesController < ApplicationController
  before_action :set_roles, only: %i[index list]
  before_action :set_role, only: %i[show edit update destroy apply_permission]
  before_action :set_permissions, only: %i[show apply_permission]

  # GET /roles or /roles.json
  def index; end

  def list
    render(partial: 'roles/table', locals: { roles: @roles })
  end

  # GET /roles/1 or /roles/1.json
  def show; end

  # GET /roles/new
  def new
    authorize Role
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit; end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)
    authorize @role

    respond_to do |format|
      if @role.save
        flash[:success] = 'Role was successfully created.'
        format.html { redirect_to role_url(@role), notice: 'Role was successfully created.' }
      else
        flash[:error] = 'Role not created.'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        flash[:success] = 'Role was successfully updated'
        format.html { redirect_to role_url(@role), notice: 'Role was successfully updated.' }
      else
        flash[:error] = 'Role not updated.'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def apply_permission
    permission = @role.permissions.find_by(key: params[:key], action: params[:p_action])
    if permission.present?
      @role.permissions.delete(permission)
    else
      @role.permissions << Permission.find_by(key: params[:key], action: params[:p_action])
    end
    render(partial: 'permissions/table', locals: { permissions: @permissions })
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    respond_to do |format|
      if @role.destroy
        flash[:success] = 'Role was successfully destroyed.'
      else
        flash[:error] = 'Role not destroyed.'
      end
      format.html { redirect_to roles_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])

    authorize @role
  end

  def set_permissions
    @permissions = Permission.group(:key).map do |permission|
      OpenStruct.new(
        key: permission.key,
        permissions: Permission.where(key: permission.key)
      )
    end
  end

  # Only allow a list of trusted parameters through.
  def role_params
    params.require(:role).permit(:id, :name, :description, :code, :active)
  end

  def set_roles
    authorize Role
    @roles = Role.all
    sort_roles
    @pagy, @roles = pagy(@roles)
  end

  def allow_sort
    %w[id name code].include?(params[:sort_by].to_s)
  end

  def sort_roles
    return unless allow_sort

    sort = { params[:sort_by].to_sym => params[:sort_order] == 'DESC' ? 'DESC' : 'ASC' }

    @roles = @roles.order(sort)
  end
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if role.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

          <ul>
            <% role.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.text_field :name, class: "form-control", readonly: readonly %>
        <%= form.label :name %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 mb-1">
      <div class="form-floating">
        <%= form.text_field :code, class: "form-control", readonly: readonly %>
        <%= form.label :code %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-10 mb-1">
      <div class="form-floating">
        <%= form.text_field :description, class: "form-control", readonly: readonly %>
        <%= form.label :description %>
      </div>
    </div>
    <div class="col-sm-12 col-md-2 mb-1">
      <div class="form-floating">
        <%= form.select :active, [['No', false], ['Yes', true]], {}, class: "form-select", disabled: readonly %>
        <%= form.label :active %>
      </div>
    </div>
  </div>
  <% unless readonly %>
    <div class="row">
      <div class="col-12">
        <%= form.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/roles/_table.html.erb
<%= turbo_frame_tag "roles_table" do %>
  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">
              <%= sort_link(column: :id, label: '#', link: list_roles_path) %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :name, label: 'Name', link: list_roles_path) %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :code, label: 'Code', link: list_roles_path) %> 
            </th>
            <th scope="col">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% roles.each do |role| %>
            <tr>
              <td><%= role.id %></td>
              <td>
                <%= link_to role.name, role, data: { turbo: false } %>
              </td>
              <td><%= role.code %></td>
              <td>
                <div class="btn-group me-2">
                  <%= link_to role, class: "btn btn-sm btn-outline-secondary", data: { turbo: false } do %>
                    <i class="bi bi-eye"></i>
                  <% end %>
                  <% if current_user.admin? %>
                    <%= link_to edit_role_path(role), class: "btn btn-sm btn-outline-primary", data: { turbo: false } do %>
                      <i class="bi bi-pencil-square"></i>
                    <% end %>
                    <%= link_to role_path(role), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                      <i class="bi bi-trash"></i>
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render "shared/pagination" %>
<% end %>

app/views/roles/edit.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">Editing <%= @role.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <%= link_to @role, class: "btn btn-sm btn-outline-primary" do %>
              <i class="bi bi-eye"></i> Show
            <% end %>
            <%= link_to roles_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Roles
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "form", role: @role, readonly: false %>
</div>

app/views/roles/index.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Roles</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <%= link_to new_role_path, class: "btn btn-sm btn-outline-secondary" do %>
            <i class="bi bi-person-plus"></i> New Role
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render "table", roles: @roles%>
</div>

app/views/roles/new.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">New role</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <%= link_to roles_path, class: "btn btn-sm btn-outline-secondary" do %>
            <i class="bi bi-arrow-return-left"></i> Back to Roles
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", role: @role, readonly: false %>
</div>

app/views/roles/show.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2"><%= @role.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <%= link_to role_path(@role), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
              <i class="bi bi-trash"></i> Delete
            <% end %>
            <%= link_to edit_role_path(@role), class: "btn btn-sm btn-outline-primary" do %>
              <i class="bi bi-pencil-square"></i> Edit
              <% end %>
            <%= link_to roles_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Roles
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", role: @role, readonly: true %>

  <div class="row">
    <div class="col-12">
    <div class="card">
      <div class="card-body">
          <h5>Permissions</h5>
          <%= render "permissions/table", permissions: @permissions %>
        </div>
      </div>
    </div>
  </div>
</div>