config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get 'login' => 'user_sessions#signin'
  post 'login' => 'user_sessions#authenticate'
  get 'logout' => 'user_sessions#signout'

  resources :users do
    collection do
      get 'list'
    end
    patch :apply_role, on: :member
  end
  
  resources :roles do
    collection do
      get 'list'
    end
    patch :apply_permission, on: :member
  end

  resources :plans, module: :client, as: :client_plans do
    collection do
      get 'list'
    end
  end

  resources :charts

  resources :clients do
    collection do
      get 'list'
    end
    resources :invoices, module: :client, only: [:index, :show] do
      patch :retry, on: :member
      resources :error_logs, module: :invoice, only: [:index, :show]
    end
  end

  namespace :reports do
    get :new_clients
    get :clients_invoiced_yesterday
    get :clients_invoiced_today
    get :clients_with_error_today
    get :clients
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  include ClientsHelper

  has_many :invoices, class_name: 'Client::Invoice', inverse_of: :client, dependent: :destroy
  belongs_to :plan, foreign_key: :client_plan_id, class_name: 'Client::Plan'
  belongs_to :created_by, foreign_key: :created_by_id, class_name: 'User'

  enum document_type: {
    cnpj: 1,
    cpf: 2
  }

  before_validation :ensure_next_payment_day_be_filled

  validates :name, :document, :document_type, :payment_type, :payment_day, :discount, presence: true

  validate :discount_less_or_equal_than_plan_max_discount

  def ensure_next_payment_day_be_filled
    self.next_payment_day = payment_day if next_payment_day.nil? || next_payment_day.zero? || next_payment_day > 31
  end

  def discount_less_or_equal_than_plan_max_discount
    return if plan.present? && discount <= plan.max_discount

    errors.add(:discount, :invalid, message: 'must be less or equal than plan max discount')
  end

  def net_value
    pp = plan.price
    pp - ((pp * discount) / 100)
  end

  def error_logs
    Client::Invoice::ErrorLog.where(:client_invoice_id.in => invoices.pluck(:id))
  end

  def current_status
    @current_status ||= invoices.order(reference_date: :desc).first.status if invoices.present?
  end

  def expected_earnings_this_year
    return @expected_earnings_this_year if @expected_earnings_this_year.present?

    extra = created_at < created_at.beginning_of_year ? created_at.month : 0

    pendency_value = (12 - extra - generated_invoices_this_year) * net_value
    pendency_value = 0 if pendency_value.negative?

    late_summed = invoices.late.range_year(Time.now.in_time_zone).sum(:invoice_value)
    @expected_earnings_this_year = earnings_this_year + pendency_value + late_summed
  end

  def expected_earnings_comparisson_yearly
    @expected_earnings_comparisson_yearly ||= calculate_percentage_difference(earnings_last_year, expected_earnings_this_year)
  end

  def earnings_this_year
    @earnings_this_year ||= invoices.payed.range_year(Time.now.in_time_zone).sum(:invoice_value)
  end

  def earnings_last_year
    @earnings_last_year ||= invoices.payed.range_year(Time.now.in_time_zone.last_year).sum(:invoice_value)
  end

  def earnings_comparisson_yearly
    @earnings_comparisson_yearly ||= calculate_percentage_difference(earnings_last_month, earnings_this_year)
  end

  def errors_this_year
    @errors_this_year ||= error_logs.range_year(Time.now.in_time_zone).count
  end

  def errors_last_year
    @errors_last_year ||= error_logs.range_year(Time.now.in_time_zone.last_year).count
  end

  def errors_comparisson_yearly
    @errors_comparisson_yearly ||= calculate_percentage_difference(errors_last_year, errors_this_year)
  end

  def generated_invoices_this_year
    @generated_invoices_this_year ||= invoices.range_year_generated(Time.now.in_time_zone).count
  end

  def generated_invoices_last_year
    @generated_invoices_last_year ||= invoices.range_year_generated(Time.now.in_time_zone.last_year).count
  end

  def generated_invoices_comparisson_yearly
    @generated_invoices_comparisson_yearly ||= calculate_percentage_difference(generated_invoices_last_year, generated_invoices_this_year)
  end

  def earnings_this_month
    @earnings_this_month ||= invoices.payed.range_month(Time.now.in_time_zone).sum(:invoice_value)
  end

  def earnings_last_month
    @earnings_last_month ||= invoices.payed.range_month(Time.now.in_time_zone.last_month).sum(:invoice_value)
  end

  def earnings_comparisson_monthly
    @earnings_comparisson_monthly ||= calculate_percentage_difference(earnings_last_month, earnings_this_month)
  end

  def errors_this_month
    @errors_this_month ||= error_logs.range_month(Time.now.in_time_zone).count
  end

  def errors_last_month
    @errors_last_month ||= error_logs.range_month(Time.now.in_time_zone.last_month).count
  end

  def errors_comparisson_monthly
    @errors_comparisson_monthly ||= calculate_percentage_difference(errors_last_month, errors_this_month)
  end
end

# == Schema Information
#
# Table name: clients
#
#  id               :integer          not null, primary key
#  name             :string
#  document         :string
#  document_type    :integer
#  payment_type     :string
#  payment_day      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  discount         :float            default(0.0)
#  email            :string
#  next_payment_day :integer
#  client_plan_id   :integer
#  created_by_id    :integer
#
# Foreign Keys
#
#  client_plan_id  (client_plan_id => client_plans.id)
#  created_by_id   (created_by_id => users.id)
#

app/controllers/client/invoice/error_logs_controller.rb
# frozen_string_literal: true

class Client::Invoice::ErrorLogsController < ApplicationController
  before_action :set_client
  before_action :set_client_invoice
  before_action :set_client_invoice_error_log, only: :show
  before_action :set_error_logs, only: :index

  # GET /clients/1/invoices/1/error_logs/1 or /clients/1/invoices/1/error_logs/1.json
  def index
    render(partial: 'client/invoice/error_logs/table', locals: { error_logs: @error_logs })
  end

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client_invoice_error_log
    @error_log = @invoice.error_logs.find(params[:id])

    authorize @error_log
  end

  def set_client_invoice
    @invoice = @client.invoices.find(params[:invoice_id])
  end

  def set_client
    @client = Client.find(params[:client_id])
  end

  def set_error_logs
    authorize Client::Invoice::ErrorLog

    @error_logs = @invoice.error_logs.all
    sort_error_logs
    @pagy, @error_logs = pagy(@error_logs)
  end

  def allow_sort
    %w[id retry_number date].include?(params[:sort_by].to_s)
  end

  def sort_error_logs
    return unless allow_sort

    sort = { params[:sort_by].to_sym => params[:sort_order] == 'DESC' ? 'DESC' : 'ASC' }

    @error_logs = @error_logs.order(sort)
  end
end

app/controllers/client/invoices_controller.rb
# frozen_string_literal: true

class Client::InvoicesController < ApplicationController
  before_action :set_client
  before_action :set_invoice, only: %i[show retry]
  before_action :set_invoices, only: :index

  def index
    render(partial: 'client/invoices/table', locals: { invoices: @invoices })
  end

  # GET /clients/1/invoices/1 or /clients/1/invoices/1.json
  def show
    @pagy, @error_logs = pagy(@invoice.error_logs)
  end

  def retry
    payment_type = payment_type_param[:payment_type]
    @invoice.payment_type = payment_type if payment_type.present?
    @invoice.status = :generating
    @invoice.max_retries += 10
    respond_to do |format|
      if @invoice.save
        flash[:success] = 'Retry was successfully scheduled'
        ::GenerateInvoiceJob.perform_in(1,
                                        { 'client_id': @invoice.client_id,
                                          'date': @invoice.reference_date }.to_json)
        format.html { redirect_to client_invoice_path(@client, @invoice) }
      else
        flash[:error] = 'Retry not scheduled'
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = @client.invoices.find(params[:id] || params[:invoice_id])
    authorize @invoice
  end

  def set_client
    @client = Client.find(params[:client_id])
  end

  def payment_type_param
    params.require(:client_invoice)
  end

  def set_invoices
    authorize Client::Invoice

    @invoices = @client.invoices.all
    sort_invoices
    @pagy, @invoices = pagy(@invoices)
  end

  def allow_sort
    %w[id description payment_type reference_month status].include?(params[:sort_by].to_s)
  end

  def sort_invoices
    return unless allow_sort

    sort = { params[:sort_by].to_sym => params[:sort_order] == 'DESC' ? 'DESC' : 'ASC' }

    @invoices = @invoices.order(sort)
  end
end

app/controllers/client/plans_controller.rb
# frozen_string_literal: true

class Client::PlansController < ApplicationController
  before_action :set_client_plans, only: %i[index list]
  before_action :set_client_plan, only: %i[show edit update destroy]

  # GET /client/plans or /client/plans.json
  def index; end

  def list
    render(partial: 'client/plans/table', locals: { client_plans: @client_plans })
  end

  # GET /client/plans/1 or /client/plans/1.json
  def show
    @pagy, @client_plan.clients = pagy(@client_plan.clients)
  end

  # GET /client/plans/new
  def new
    @client_plan = Client::Plan.new
  end

  # GET /client/plans/1/edit
  def edit; end

  # POST /client/plans or /client/plans.json
  def create
    @client_plan = Client::Plan.new(client_plan_params)

    respond_to do |format|
      if @client_plan.save
        flash[:success] = 'Plan was successfully created.'
        format.html { redirect_to client_plan_url(@client_plan), notice: 'Plan was successfully created.' }
      else
        flash[:error] = 'Plan not created.'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client/plans/1 or /client/plans/1.json
  def update
    respond_to do |format|
      if @client_plan.update(client_plan_params)
        format.html { redirect_to client_plan_url(@client_plan), notice: 'Plan was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client/plans/1 or /client/plans/1.json
  def destroy
    respond_to do |format|
      if @client_plan.destroy
        flash[:success] = 'Plan was successfully destroyed.'
      else
        flash[:error] = 'Plan not deleted'
      end
      format.html { redirect_to client_plans_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client_plan
    @client_plan = Client::Plan.find(params[:id])
    authorize @client_plan
  end

  # Only allow a list of trusted parameters through.
  def client_plan_params
    params.require(:client_plan).permit(:name, :description, :price, :signable,
                                        :start_date, :end_date, :billable_period,
                                        :max_discount, :commissionable, :sale, :code)
  end

  def set_client_plans
    authorize Client::Plan

    @client_plans = Client::Plan.all
    sort_client_plans
    @pagy, @client_plans = pagy(@client_plans)
  end

  def allow_sort
    %w[id name price start_date end_date].include?(params[:sort_by].to_s)
  end

  def sort_client_plans
    return unless allow_sort

    sort = { params[:sort_by].to_sym => params[:sort_order] == 'DESC' ? 'DESC' : 'ASC' }

    @client_plans = @client_plans.order(sort)
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_clients, only: %i[index list]
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients or /clients.json
  def index; end

  # GET /clients/1 or /clients/1.json
  def show
    @pagy, @client.invoices = pagy(@client.invoices)
  end

  # GET /clients/new
  def new
    authorize Client
    @client = Client.new
    @client.created_by = current_user
    @client
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients or /clients.json
  def create
    @client = Client.new(new_client_params)
    authorize @client

    @client.created_by_id = current_user.id

    respond_to do |format|
      if @client.save
        flash[:success] = 'Client was successfully created.'
        format.html { redirect_to client_url(@client) }
      else
        flash[:error] = 'Client not created.'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(update_client_params)
        flash[:success] = 'Client was successfully updated'
        format.html { redirect_to client_url(@client) }
      else
        flash[:error] = 'Client not updated.'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    respond_to do |format|
      if @client.destroy
        flash[:success] = 'Client was successfully destroyed.'
      else
        flash[:error] = 'Client not destroyed.'
      end
      format.html { redirect_to clients_url }
    end
  end

  def list
    render(partial: 'clients/table', locals: { clients: @clients, is_report: false })
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
    authorize @client
  end

  # Only allow a list of trusted parameters through.
  def new_client_params
    params.require(:client).permit(:name, :document, :document_type, :payment_type, :payment_day, :discount, :email, :client_plan_id)
  end

  def update_client_params
    params.require(:client).permit(:name, :document, :document_type, :payment_type, :next_payment_day, :discount, :email, :client_plan_id)
  end

  def set_clients
    authorize Client

    @clients = Client.all
    sort_clients
    @pagy, @clients = pagy(@clients)
  end

  def allow_sort
    %w[id name document document_type].include?(params[:sort_by].to_s)
  end

  def sort_clients
    return unless allow_sort

    sort = { params[:sort_by].to_sym => params[:sort_order] == 'DESC' ? 'DESC' : 'ASC' }

    @clients = @clients.order(sort)
  end
end

app/helpers/client/invoice/error_logs_helper.rb
# frozen_string_literal: true

module Client::Invoice::ErrorLogsHelper
end

app/helpers/client/invoices_helper.rb
# frozen_string_literal: true

module Client::InvoicesHelper
end

app/helpers/client/plans_helper.rb
# frozen_string_literal: true

module Client::PlansHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
  def earnings_this_year
    Client::Invoice.payed.range_year(Time.now.in_time_zone).sum(:invoice_value)
  end

  def earnings_last_year
    Client::Invoice.payed.range_year(Time.now.in_time_zone.last_year).sum(:invoice_value)
  end

  def earnings_comparisson_yearly
    calculate_percentage_difference(earnings_last_year, earnings_this_year)
  end

  def errors_this_year
    Client::Invoice::ErrorLog.range_year(Time.now.in_time_zone).count
  end

  def errors_last_year
    Client::Invoice::ErrorLog.range_year(Time.now.in_time_zone.last_year).count
  end

  def errors_comparisson_yearly
    calculate_percentage_difference(errors_last_year, errors_this_year)
  end

  def generated_invoices_this_year
    Client::Invoice.range_year_generated(Time.now.in_time_zone).count
  end

  def generated_invoices_last_year
    Client::Invoice.range_year_generated(Time.now.in_time_zone.last_year).count
  end

  def generated_invoices_comparisson_yearly
    calculate_percentage_difference(generated_invoices_last_year, generated_invoices_this_year)
  end

  def generated_invoices_this_month
    Client::Invoice.range_month_generated(Time.now.in_time_zone).count
  end

  def generated_invoices_last_month
    Client::Invoice.range_month_generated(Time.now.in_time_zone.last_year).count
  end

  def generated_invoices_comparisson_monthly
    calculate_percentage_difference(generated_invoices_last_month, generated_invoices_this_month)
  end

  def earnings_this_month
    Client::Invoice.payed.range_month(Time.now.in_time_zone).sum(:invoice_value)
  end

  def earnings_last_month
    Client::Invoice.payed.range_month(Time.now.in_time_zone.last_month).sum(:invoice_value)
  end

  def earnings_comparisson_monthly
    calculate_percentage_difference(earnings_last_month, earnings_this_month)
  end

  def errors_this_month
    Client::Invoice::ErrorLog.range_month(Time.now.in_time_zone).count
  end

  def errors_last_month
    Client::Invoice::ErrorLog.range_month(Time.now.in_time_zone.last_month).count
  end

  def errors_comparisson_monthly
    calculate_percentage_difference(errors_last_month, errors_this_month)
  end

  def calculate_percentage_difference(number1, number2)
    return 100 if number1.zero? && number2.nonzero?
    return -100 if number2.zero? && number1.nonzero?
    return 0 if number2.zero? && number1.zero?

    difference = number2 - number1
    percentage_difference = (difference.to_f / number1) * 100
    percentage_difference.round(2)
  end
end

app/views/client/plans/_form.html.erb
<%= form_with(model: client_plan) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if client_plan.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(client_plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

          <ul>
            <% client_plan.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-4 mb-1">
      <div class="form-floating">
        <%= form.text_field :name, class: "form-control", readonly: readonly %>
        <%= form.label :name %>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 mb-1">
      <div class="form-floating">
        <%= form.datetime_field :start_date, class: "form-control", readonly: readonly %>
        <%= form.label :start_date %>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 mb-1">
      <div class="form-floating">
        <%= form.datetime_field :end_date, class: "form-control", readonly: readonly %>
        <%= form.label :end_date %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 mb-1">
      <div class="form-floating">
        <%= form.text_field :description, class: "form-control", readonly: readonly %>
        <%= form.label :description %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-4 mb-1">
      <div class="form-floating">
        <%= form.text_field :cpde, class: "form-control", readonly: readonly %>
        <%= form.label :code %>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 mb-1">
      <div class="form-floating">
        <%= form.select :billable_period, Client::PlanPresenter.billable_period_options, {}, class: "form-select", disabled: readonly %>
        <%= form.label :billable_period %>
      </div>
    </div>
    <div class="col-sm-12 col-md-2 mb-1">
      <div class="form-floating">
        <%= form.number_field :price, class: "form-control", readonly: readonly, step: 0.01 %>
        <%= form.label :price %>
      </div>
    </div>
    <div class="col-sm-12 col-md-2 mb-1">
      <div class="form-floating">
        <%= form.number_field :max_discount, class: "form-control", readonly: readonly, min: 0, max: 100, step: 0.01 %>
        <%= form.label :max_discount %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-md-2 col-lg-1 mb-1 mr-1">
      <div class="form-check form-switch">
        <%= form.check_box :sale, class: "form-check-input", disabled: readonly %>
        <%= form.label :sale, class: "form-check-label" %>
      </div>
    </div>
    <div class="col-sm-4 col-md-2 col-lg-1 mb-1 mr-1">
      <div class="form-check form-switch">
        <%= form.check_box :signable, class: "form-check-input", disabled: readonly %>
        <%= form.label :signable, class: "form-check-label" %>
      </div>
    </div>
    <div class="col-sm-4 col-md-2 col-lg-1 mb-1 mr-1">
      <div class="form-check form-switch">
        <%= form.check_box :commissionable, class: "form-check-input", disabled: readonly %>
        <%= form.label :commissionable, class: "form-check-label" %>
      </div>
    </div>
  </div>
  <% unless readonly %>
    <div class="row">
      <div class="col-12">
        <%= form.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/client/plans/_table.html.erb
<%= turbo_frame_tag "client_plans_table" do %>
  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">
              <%= sort_link(column: :id, label: '#', controller: :plans, action: 'list') %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :name, label: 'Name', controller: :plans, action: 'list') %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :price, label: 'Price', controller: :plans, action: 'list') %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :start_date, label: 'Start Date', controller: :plans, action: 'list') %> 
            </th>
            <th scope="col">
              <%= sort_link(column: :end_date, label: 'End Date', controller: :plans, action: 'list') %> 
            </th>
            <th scope="col">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% client_plans.each do |client_plan| %>
            <tr>
              <td><%= client_plan.id %></td>
              <td>
                <%= link_to client_plan.name, client_plan, data: { turbo: false } %>
              </td>
              <td><%= number_to_currency(client_plan.price) %></td>
              <td><%= client_plan.start_date %></td>
              <td><%= client_plan.end_date %></td>
              <td>
                <div class="btn-group me-2">
                  <%= link_to client_plan, class: "btn btn-sm btn-outline-secondary", data: { turbo: false } do %>
                    <i class="bi bi-eye"></i>
                  <% end %>
                  <% if current_user.admin? %>
                    <%= link_to edit_client_plan_path(client_plan), class: "btn btn-sm btn-outline-primary", data: { turbo: false } do %>
                      <i class="bi bi-pencil-square"></i>
                    <% end %>
                    <%= link_to client_plan_path(client_plan), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                      <i class="bi bi-trash"></i>
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render "shared/pagination" %>
<% end %>

app/views/client/plans/edit.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">Editing <%= @client_plan.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <%= link_to "Show", @client_plan, class: "btn btn-sm btn-outline-primary" %>
            <%= link_to "Back to plans", client_plans_path, class: "btn btn-sm btn-outline-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render "form", client_plan: @client_plan, readonly: false %>
</div>

app/views/client/plans/index.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Plans</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <% if current_user.admin? %>
            <%= link_to new_client_plan_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-plus-circle"></i> New plan
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render "table", client_plans: @client_plans %>
    </div>
  </div>
</div>

app/views/client/plans/new.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row mb-1">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">New plan</h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
            <%= link_to client_plans_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Plans
            <% end %>
          </div>
      </div>
    </div>
  </div>

<%= render "form", client_plan: @client_plan, readonly: false %>

</div>

app/views/client/plans/show.html.erb
<%= render "shared/menu" %>
<div class="col-sm p-3 min-vh-100">
  <%= render 'shared/notices' %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
        <h1 class="h2">
          <%= @client_plan.name %>
        </h1>
        <div class="btn-toolbar mb-2 mb-md-0 mx-2">
          <div class="btn-group me-2">
            <% if current_user.admin? %>
              <%= link_to client_plan_path(@client_plan), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
                <i class="bi bi-trash"></i> Delete
              <% end %>
              <%= link_to edit_client_plan_path(@client_plan), class: "btn btn-sm btn-outline-primary" do %>
                <i class="bi bi-pencil-square"></i> Edit
              <% end %>
            <% end %>
            <%= link_to client_plans_path, class: "btn btn-sm btn-outline-secondary" do %>
              <i class="bi bi-arrow-return-left"></i> Back to Plans
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <div class="card mx-3">
        <div class="card-body">
          <h5 class="card-title">Data</h5>
          <%= render "form", client_plan: @client_plan, readonly: true %>
        </div>
      </div>
    </div>
  </div>

  
  <div class="row mt-2">
    <div class="col-12">
      <div class="card mx-3">
        <div class="card-body">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 border-bottom">
            <h5 class="card-title">Clients</h5>
          </div>
          <div class="row">
            <div class="col-12">
              <%= render "clients/table", clients: @client_plan.clients, is_report: true %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>